logbook:
  format:
    style: json
  filter:
    type: request
    match:
      - path: /api/sensitive

logging:
  level:
    org.zalando.logbook: WARN

spring:
  sql:
    init:
      mode: ALWAYS

  datasource:
    url: jdbc:h2:file:./db/filmorate
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
